apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Namespace }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: {{ .Release.Namespace }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: {{ .Release.Namespace }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: redis
        image: redis:5.0.4
        command:
        - redis-server
        - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
    {{- if $.Values.limits }}
        resources:
          limits:
            memory: {{ $.Values.limits.memory }}
            cpu: {{ $.Values.limits.cpu }}
    {{- end }}
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: redis-config-map
          items:
          - key: redis-config
            path: redis.conf
